# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nautilus.proto import nautilus_pb2 as nautilus_dot_proto_dot_nautilus__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nautilus/proto/nautilus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyServiceStub(object):
    """─── Strategy Management ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListStrategies = channel.unary_unary(
                '/tradefox.nautilus.StrategyService/ListStrategies',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyList.FromString,
                _registered_method=True)
        self.DeployStrategy = channel.unary_unary(
                '/tradefox.nautilus.StrategyService/DeployStrategy',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.DeployRequest.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.DeployResponse.FromString,
                _registered_method=True)
        self.StopStrategy = channel.unary_unary(
                '/tradefox.nautilus.StrategyService/StopStrategy',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyId.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetStrategyState = channel.unary_unary(
                '/tradefox.nautilus.StrategyService/GetStrategyState',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyId.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyState.FromString,
                _registered_method=True)
        self.StreamSignals = channel.unary_stream(
                '/tradefox.nautilus.StrategyService/StreamSignals',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyId.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.Signal.FromString,
                _registered_method=True)


class StrategyServiceServicer(object):
    """─── Strategy Management ───

    """

    def ListStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategyState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSignals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStrategies,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyList.SerializeToString,
            ),
            'DeployStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployStrategy,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.DeployRequest.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.DeployResponse.SerializeToString,
            ),
            'StopStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStrategy,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyId.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.StatusResponse.SerializeToString,
            ),
            'GetStrategyState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategyState,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyId.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyState.SerializeToString,
            ),
            'StreamSignals': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSignals,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.StrategyId.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.Signal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradefox.nautilus.StrategyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradefox.nautilus.StrategyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyService(object):
    """─── Strategy Management ───

    """

    @staticmethod
    def ListStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.StrategyService/ListStrategies',
            nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.StrategyList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.StrategyService/DeployStrategy',
            nautilus_dot_proto_dot_nautilus__pb2.DeployRequest.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.StrategyService/StopStrategy',
            nautilus_dot_proto_dot_nautilus__pb2.StrategyId.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStrategyState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.StrategyService/GetStrategyState',
            nautilus_dot_proto_dot_nautilus__pb2.StrategyId.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.StrategyState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tradefox.nautilus.StrategyService/StreamSignals',
            nautilus_dot_proto_dot_nautilus__pb2.StrategyId.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.Signal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExecutionServiceStub(object):
    """─── Order Execution ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOrder = channel.unary_unary(
                '/tradefox.nautilus.ExecutionService/SubmitOrder',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.OrderRequest.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/tradefox.nautilus.ExecutionService/CancelOrder',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.CancelRequest.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ModifyOrder = channel.unary_unary(
                '/tradefox.nautilus.ExecutionService/ModifyOrder',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.ModifyRequest.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.StreamOrderUpdates = channel.unary_stream(
                '/tradefox.nautilus.ExecutionService/StreamOrderUpdates',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.OrderUpdate.FromString,
                _registered_method=True)
        self.StreamPositionUpdates = channel.unary_stream(
                '/tradefox.nautilus.ExecutionService/StreamPositionUpdates',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.PositionUpdate.FromString,
                _registered_method=True)


class ExecutionServiceServicer(object):
    """─── Order Execution ───

    """

    def SubmitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOrderUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPositionUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.OrderRequest.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.OrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.CancelRequest.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.StatusResponse.SerializeToString,
            ),
            'ModifyOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyOrder,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.ModifyRequest.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.OrderResponse.SerializeToString,
            ),
            'StreamOrderUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOrderUpdates,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.OrderUpdate.SerializeToString,
            ),
            'StreamPositionUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPositionUpdates,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.PositionUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradefox.nautilus.ExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradefox.nautilus.ExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionService(object):
    """─── Order Execution ───

    """

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.ExecutionService/SubmitOrder',
            nautilus_dot_proto_dot_nautilus__pb2.OrderRequest.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.ExecutionService/CancelOrder',
            nautilus_dot_proto_dot_nautilus__pb2.CancelRequest.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.ExecutionService/ModifyOrder',
            nautilus_dot_proto_dot_nautilus__pb2.ModifyRequest.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOrderUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tradefox.nautilus.ExecutionService/StreamOrderUpdates',
            nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.OrderUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPositionUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tradefox.nautilus.ExecutionService/StreamPositionUpdates',
            nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.PositionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PortfolioServiceStub(object):
    """─── Portfolio & Risk ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPortfolio = channel.unary_unary(
                '/tradefox.nautilus.PortfolioService/GetPortfolio',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.Portfolio.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/tradefox.nautilus.PortfolioService/GetPositions',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.PositionFilter.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.PositionList.FromString,
                _registered_method=True)
        self.GetRiskMetrics = channel.unary_unary(
                '/tradefox.nautilus.PortfolioService/GetRiskMetrics',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.RiskMetrics.FromString,
                _registered_method=True)
        self.StreamPnL = channel.unary_stream(
                '/tradefox.nautilus.PortfolioService/StreamPnL',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.PnLUpdate.FromString,
                _registered_method=True)


class PortfolioServiceServicer(object):
    """─── Portfolio & Risk ───

    """

    def GetPortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRiskMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPnL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolio,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.Portfolio.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.PositionFilter.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.PositionList.SerializeToString,
            ),
            'GetRiskMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRiskMetrics,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.RiskMetrics.SerializeToString,
            ),
            'StreamPnL': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPnL,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.PnLUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradefox.nautilus.PortfolioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradefox.nautilus.PortfolioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortfolioService(object):
    """─── Portfolio & Risk ───

    """

    @staticmethod
    def GetPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.PortfolioService/GetPortfolio',
            nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.Portfolio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.PortfolioService/GetPositions',
            nautilus_dot_proto_dot_nautilus__pb2.PositionFilter.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.PositionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRiskMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.PortfolioService/GetRiskMetrics',
            nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.RiskMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPnL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tradefox.nautilus.PortfolioService/StreamPnL',
            nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.PnLUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BacktestServiceStub(object):
    """─── Backtesting ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunBacktest = channel.unary_stream(
                '/tradefox.nautilus.BacktestService/RunBacktest',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestConfig.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestProgress.FromString,
                _registered_method=True)
        self.GetBacktestResult = channel.unary_unary(
                '/tradefox.nautilus.BacktestService/GetBacktestResult',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestId.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestResult.FromString,
                _registered_method=True)
        self.ListBacktests = channel.unary_unary(
                '/tradefox.nautilus.BacktestService/ListBacktests',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestList.FromString,
                _registered_method=True)
        self.CompareStrategies = channel.unary_unary(
                '/tradefox.nautilus.BacktestService/CompareStrategies',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.CompareRequest.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.CompareResult.FromString,
                _registered_method=True)


class BacktestServiceServicer(object):
    """─── Backtesting ───

    """

    def RunBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBacktests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BacktestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunBacktest': grpc.unary_stream_rpc_method_handler(
                    servicer.RunBacktest,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestConfig.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestProgress.SerializeToString,
            ),
            'GetBacktestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktestResult,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestId.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestResult.SerializeToString,
            ),
            'ListBacktests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBacktests,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.Empty.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.BacktestList.SerializeToString,
            ),
            'CompareStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareStrategies,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.CompareRequest.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.CompareResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradefox.nautilus.BacktestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradefox.nautilus.BacktestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BacktestService(object):
    """─── Backtesting ───

    """

    @staticmethod
    def RunBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tradefox.nautilus.BacktestService/RunBacktest',
            nautilus_dot_proto_dot_nautilus__pb2.BacktestConfig.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.BacktestProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.BacktestService/GetBacktestResult',
            nautilus_dot_proto_dot_nautilus__pb2.BacktestId.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.BacktestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBacktests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.BacktestService/ListBacktests',
            nautilus_dot_proto_dot_nautilus__pb2.Empty.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.BacktestList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.BacktestService/CompareStrategies',
            nautilus_dot_proto_dot_nautilus__pb2.CompareRequest.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.CompareResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataServiceStub(object):
    """─── Data Catalog ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListInstruments = channel.unary_unary(
                '/tradefox.nautilus.DataService/ListInstruments',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.InstrumentFilter.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.InstrumentList.FromString,
                _registered_method=True)
        self.ImportData = channel.unary_stream(
                '/tradefox.nautilus.DataService/ImportData',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.ImportRequest.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.ImportProgress.FromString,
                _registered_method=True)
        self.GetDataRange = channel.unary_unary(
                '/tradefox.nautilus.DataService/GetDataRange',
                request_serializer=nautilus_dot_proto_dot_nautilus__pb2.DataRangeRequest.SerializeToString,
                response_deserializer=nautilus_dot_proto_dot_nautilus__pb2.DataRange.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """─── Data Catalog ───

    """

    def ListInstruments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListInstruments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstruments,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.InstrumentFilter.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.InstrumentList.SerializeToString,
            ),
            'ImportData': grpc.unary_stream_rpc_method_handler(
                    servicer.ImportData,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.ImportRequest.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.ImportProgress.SerializeToString,
            ),
            'GetDataRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataRange,
                    request_deserializer=nautilus_dot_proto_dot_nautilus__pb2.DataRangeRequest.FromString,
                    response_serializer=nautilus_dot_proto_dot_nautilus__pb2.DataRange.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradefox.nautilus.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradefox.nautilus.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """─── Data Catalog ───

    """

    @staticmethod
    def ListInstruments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.DataService/ListInstruments',
            nautilus_dot_proto_dot_nautilus__pb2.InstrumentFilter.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.InstrumentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tradefox.nautilus.DataService/ImportData',
            nautilus_dot_proto_dot_nautilus__pb2.ImportRequest.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.ImportProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDataRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradefox.nautilus.DataService/GetDataRange',
            nautilus_dot_proto_dot_nautilus__pb2.DataRangeRequest.SerializeToString,
            nautilus_dot_proto_dot_nautilus__pb2.DataRange.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
