// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: nautilus/proto/nautilus.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StrategyService_ListStrategies_FullMethodName   = "/tradefox.nautilus.StrategyService/ListStrategies"
	StrategyService_DeployStrategy_FullMethodName   = "/tradefox.nautilus.StrategyService/DeployStrategy"
	StrategyService_StopStrategy_FullMethodName     = "/tradefox.nautilus.StrategyService/StopStrategy"
	StrategyService_GetStrategyState_FullMethodName = "/tradefox.nautilus.StrategyService/GetStrategyState"
	StrategyService_StreamSignals_FullMethodName    = "/tradefox.nautilus.StrategyService/StreamSignals"
)

// StrategyServiceClient is the client API for StrategyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyServiceClient interface {
	ListStrategies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StrategyList, error)
	DeployStrategy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
	StopStrategy(ctx context.Context, in *StrategyId, opts ...grpc.CallOption) (*StatusResponse, error)
	GetStrategyState(ctx context.Context, in *StrategyId, opts ...grpc.CallOption) (*StrategyState, error)
	StreamSignals(ctx context.Context, in *StrategyId, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Signal], error)
}

type strategyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyServiceClient(cc grpc.ClientConnInterface) StrategyServiceClient {
	return &strategyServiceClient{cc}
}

func (c *strategyServiceClient) ListStrategies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StrategyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyList)
	err := c.cc.Invoke(ctx, StrategyService_ListStrategies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) DeployStrategy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, StrategyService_DeployStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) StopStrategy(ctx context.Context, in *StrategyId, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, StrategyService_StopStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) GetStrategyState(ctx context.Context, in *StrategyId, opts ...grpc.CallOption) (*StrategyState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyState)
	err := c.cc.Invoke(ctx, StrategyService_GetStrategyState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) StreamSignals(ctx context.Context, in *StrategyId, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Signal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StrategyService_ServiceDesc.Streams[0], StrategyService_StreamSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StrategyId, Signal]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StrategyService_StreamSignalsClient = grpc.ServerStreamingClient[Signal]

// StrategyServiceServer is the server API for StrategyService service.
// All implementations must embed UnimplementedStrategyServiceServer
// for forward compatibility.
type StrategyServiceServer interface {
	ListStrategies(context.Context, *Empty) (*StrategyList, error)
	DeployStrategy(context.Context, *DeployRequest) (*DeployResponse, error)
	StopStrategy(context.Context, *StrategyId) (*StatusResponse, error)
	GetStrategyState(context.Context, *StrategyId) (*StrategyState, error)
	StreamSignals(*StrategyId, grpc.ServerStreamingServer[Signal]) error
	mustEmbedUnimplementedStrategyServiceServer()
}

// UnimplementedStrategyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyServiceServer struct{}

func (UnimplementedStrategyServiceServer) ListStrategies(context.Context, *Empty) (*StrategyList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStrategies not implemented")
}
func (UnimplementedStrategyServiceServer) DeployStrategy(context.Context, *DeployRequest) (*DeployResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployStrategy not implemented")
}
func (UnimplementedStrategyServiceServer) StopStrategy(context.Context, *StrategyId) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopStrategy not implemented")
}
func (UnimplementedStrategyServiceServer) GetStrategyState(context.Context, *StrategyId) (*StrategyState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStrategyState not implemented")
}
func (UnimplementedStrategyServiceServer) StreamSignals(*StrategyId, grpc.ServerStreamingServer[Signal]) error {
	return status.Error(codes.Unimplemented, "method StreamSignals not implemented")
}
func (UnimplementedStrategyServiceServer) mustEmbedUnimplementedStrategyServiceServer() {}
func (UnimplementedStrategyServiceServer) testEmbeddedByValue()                         {}

// UnsafeStrategyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyServiceServer will
// result in compilation errors.
type UnsafeStrategyServiceServer interface {
	mustEmbedUnimplementedStrategyServiceServer()
}

func RegisterStrategyServiceServer(s grpc.ServiceRegistrar, srv StrategyServiceServer) {
	// If the following call panics, it indicates UnimplementedStrategyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StrategyService_ServiceDesc, srv)
}

func _StrategyService_ListStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).ListStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_ListStrategies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).ListStrategies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_DeployStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).DeployStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_DeployStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).DeployStrategy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_StopStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).StopStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_StopStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).StopStrategy(ctx, req.(*StrategyId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_GetStrategyState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).GetStrategyState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_GetStrategyState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).GetStrategyState(ctx, req.(*StrategyId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_StreamSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StrategyId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StrategyServiceServer).StreamSignals(m, &grpc.GenericServerStream[StrategyId, Signal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StrategyService_StreamSignalsServer = grpc.ServerStreamingServer[Signal]

// StrategyService_ServiceDesc is the grpc.ServiceDesc for StrategyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StrategyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradefox.nautilus.StrategyService",
	HandlerType: (*StrategyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStrategies",
			Handler:    _StrategyService_ListStrategies_Handler,
		},
		{
			MethodName: "DeployStrategy",
			Handler:    _StrategyService_DeployStrategy_Handler,
		},
		{
			MethodName: "StopStrategy",
			Handler:    _StrategyService_StopStrategy_Handler,
		},
		{
			MethodName: "GetStrategyState",
			Handler:    _StrategyService_GetStrategyState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignals",
			Handler:       _StrategyService_StreamSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nautilus/proto/nautilus.proto",
}

const (
	ExecutionService_SubmitOrder_FullMethodName           = "/tradefox.nautilus.ExecutionService/SubmitOrder"
	ExecutionService_CancelOrder_FullMethodName           = "/tradefox.nautilus.ExecutionService/CancelOrder"
	ExecutionService_ModifyOrder_FullMethodName           = "/tradefox.nautilus.ExecutionService/ModifyOrder"
	ExecutionService_StreamOrderUpdates_FullMethodName    = "/tradefox.nautilus.ExecutionService/StreamOrderUpdates"
	ExecutionService_StreamPositionUpdates_FullMethodName = "/tradefox.nautilus.ExecutionService/StreamPositionUpdates"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionServiceClient interface {
	SubmitOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	CancelOrder(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ModifyOrder(ctx context.Context, in *ModifyRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	StreamOrderUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderUpdate], error)
	StreamPositionUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionUpdate], error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) SubmitOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, ExecutionService_SubmitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) CancelOrder(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ExecutionService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) ModifyOrder(ctx context.Context, in *ModifyRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ModifyOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) StreamOrderUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutionService_ServiceDesc.Streams[0], ExecutionService_StreamOrderUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, OrderUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_StreamOrderUpdatesClient = grpc.ServerStreamingClient[OrderUpdate]

func (c *executionServiceClient) StreamPositionUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutionService_ServiceDesc.Streams[1], ExecutionService_StreamPositionUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, PositionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_StreamPositionUpdatesClient = grpc.ServerStreamingClient[PositionUpdate]

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
type ExecutionServiceServer interface {
	SubmitOrder(context.Context, *OrderRequest) (*OrderResponse, error)
	CancelOrder(context.Context, *CancelRequest) (*StatusResponse, error)
	ModifyOrder(context.Context, *ModifyRequest) (*OrderResponse, error)
	StreamOrderUpdates(*Empty, grpc.ServerStreamingServer[OrderUpdate]) error
	StreamPositionUpdates(*Empty, grpc.ServerStreamingServer[PositionUpdate]) error
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) SubmitOrder(context.Context, *OrderRequest) (*OrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (UnimplementedExecutionServiceServer) CancelOrder(context.Context, *CancelRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedExecutionServiceServer) ModifyOrder(context.Context, *ModifyRequest) (*OrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifyOrder not implemented")
}
func (UnimplementedExecutionServiceServer) StreamOrderUpdates(*Empty, grpc.ServerStreamingServer[OrderUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamOrderUpdates not implemented")
}
func (UnimplementedExecutionServiceServer) StreamPositionUpdates(*Empty, grpc.ServerStreamingServer[PositionUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamPositionUpdates not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_SubmitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).SubmitOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).CancelOrder(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_ModifyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ModifyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ModifyOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ModifyOrder(ctx, req.(*ModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_StreamOrderUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExecutionServiceServer).StreamOrderUpdates(m, &grpc.GenericServerStream[Empty, OrderUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_StreamOrderUpdatesServer = grpc.ServerStreamingServer[OrderUpdate]

func _ExecutionService_StreamPositionUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExecutionServiceServer).StreamPositionUpdates(m, &grpc.GenericServerStream[Empty, PositionUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_StreamPositionUpdatesServer = grpc.ServerStreamingServer[PositionUpdate]

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradefox.nautilus.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _ExecutionService_SubmitOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _ExecutionService_CancelOrder_Handler,
		},
		{
			MethodName: "ModifyOrder",
			Handler:    _ExecutionService_ModifyOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOrderUpdates",
			Handler:       _ExecutionService_StreamOrderUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPositionUpdates",
			Handler:       _ExecutionService_StreamPositionUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nautilus/proto/nautilus.proto",
}

const (
	PortfolioService_GetPortfolio_FullMethodName   = "/tradefox.nautilus.PortfolioService/GetPortfolio"
	PortfolioService_GetPositions_FullMethodName   = "/tradefox.nautilus.PortfolioService/GetPositions"
	PortfolioService_GetRiskMetrics_FullMethodName = "/tradefox.nautilus.PortfolioService/GetRiskMetrics"
	PortfolioService_StreamPnL_FullMethodName      = "/tradefox.nautilus.PortfolioService/StreamPnL"
)

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	GetPortfolio(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Portfolio, error)
	GetPositions(ctx context.Context, in *PositionFilter, opts ...grpc.CallOption) (*PositionList, error)
	GetRiskMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RiskMetrics, error)
	StreamPnL(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PnLUpdate], error)
}

type portfolioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioServiceClient(cc grpc.ClientConnInterface) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) GetPortfolio(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Portfolio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Portfolio)
	err := c.cc.Invoke(ctx, PortfolioService_GetPortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetPositions(ctx context.Context, in *PositionFilter, opts ...grpc.CallOption) (*PositionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionList)
	err := c.cc.Invoke(ctx, PortfolioService_GetPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetRiskMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RiskMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskMetrics)
	err := c.cc.Invoke(ctx, PortfolioService_GetRiskMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) StreamPnL(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PnLUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PortfolioService_ServiceDesc.Streams[0], PortfolioService_StreamPnL_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, PnLUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PortfolioService_StreamPnLClient = grpc.ServerStreamingClient[PnLUpdate]

// PortfolioServiceServer is the server API for PortfolioService service.
// All implementations must embed UnimplementedPortfolioServiceServer
// for forward compatibility.
type PortfolioServiceServer interface {
	GetPortfolio(context.Context, *Empty) (*Portfolio, error)
	GetPositions(context.Context, *PositionFilter) (*PositionList, error)
	GetRiskMetrics(context.Context, *Empty) (*RiskMetrics, error)
	StreamPnL(*Empty, grpc.ServerStreamingServer[PnLUpdate]) error
	mustEmbedUnimplementedPortfolioServiceServer()
}

// UnimplementedPortfolioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortfolioServiceServer struct{}

func (UnimplementedPortfolioServiceServer) GetPortfolio(context.Context, *Empty) (*Portfolio, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortfolio not implemented")
}
func (UnimplementedPortfolioServiceServer) GetPositions(context.Context, *PositionFilter) (*PositionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPositions not implemented")
}
func (UnimplementedPortfolioServiceServer) GetRiskMetrics(context.Context, *Empty) (*RiskMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRiskMetrics not implemented")
}
func (UnimplementedPortfolioServiceServer) StreamPnL(*Empty, grpc.ServerStreamingServer[PnLUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamPnL not implemented")
}
func (UnimplementedPortfolioServiceServer) mustEmbedUnimplementedPortfolioServiceServer() {}
func (UnimplementedPortfolioServiceServer) testEmbeddedByValue()                          {}

// UnsafePortfolioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServiceServer will
// result in compilation errors.
type UnsafePortfolioServiceServer interface {
	mustEmbedUnimplementedPortfolioServiceServer()
}

func RegisterPortfolioServiceServer(s grpc.ServiceRegistrar, srv PortfolioServiceServer) {
	// If the following call panics, it indicates UnimplementedPortfolioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortfolioService_ServiceDesc, srv)
}

func _PortfolioService_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetPortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetPositions(ctx, req.(*PositionFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetRiskMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetRiskMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetRiskMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetRiskMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_StreamPnL_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServiceServer).StreamPnL(m, &grpc.GenericServerStream[Empty, PnLUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PortfolioService_StreamPnLServer = grpc.ServerStreamingServer[PnLUpdate]

// PortfolioService_ServiceDesc is the grpc.ServiceDesc for PortfolioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortfolioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradefox.nautilus.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPortfolio",
			Handler:    _PortfolioService_GetPortfolio_Handler,
		},
		{
			MethodName: "GetPositions",
			Handler:    _PortfolioService_GetPositions_Handler,
		},
		{
			MethodName: "GetRiskMetrics",
			Handler:    _PortfolioService_GetRiskMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPnL",
			Handler:       _PortfolioService_StreamPnL_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nautilus/proto/nautilus.proto",
}

const (
	BacktestService_RunBacktest_FullMethodName       = "/tradefox.nautilus.BacktestService/RunBacktest"
	BacktestService_GetBacktestResult_FullMethodName = "/tradefox.nautilus.BacktestService/GetBacktestResult"
	BacktestService_ListBacktests_FullMethodName     = "/tradefox.nautilus.BacktestService/ListBacktests"
	BacktestService_CompareStrategies_FullMethodName = "/tradefox.nautilus.BacktestService/CompareStrategies"
)

// BacktestServiceClient is the client API for BacktestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BacktestServiceClient interface {
	RunBacktest(ctx context.Context, in *BacktestConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BacktestProgress], error)
	GetBacktestResult(ctx context.Context, in *BacktestId, opts ...grpc.CallOption) (*BacktestResult, error)
	ListBacktests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BacktestList, error)
	CompareStrategies(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResult, error)
}

type backtestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBacktestServiceClient(cc grpc.ClientConnInterface) BacktestServiceClient {
	return &backtestServiceClient{cc}
}

func (c *backtestServiceClient) RunBacktest(ctx context.Context, in *BacktestConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BacktestProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BacktestService_ServiceDesc.Streams[0], BacktestService_RunBacktest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BacktestConfig, BacktestProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BacktestService_RunBacktestClient = grpc.ServerStreamingClient[BacktestProgress]

func (c *backtestServiceClient) GetBacktestResult(ctx context.Context, in *BacktestId, opts ...grpc.CallOption) (*BacktestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BacktestResult)
	err := c.cc.Invoke(ctx, BacktestService_GetBacktestResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestServiceClient) ListBacktests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BacktestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BacktestList)
	err := c.cc.Invoke(ctx, BacktestService_ListBacktests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backtestServiceClient) CompareStrategies(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareResult)
	err := c.cc.Invoke(ctx, BacktestService_CompareStrategies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BacktestServiceServer is the server API for BacktestService service.
// All implementations must embed UnimplementedBacktestServiceServer
// for forward compatibility.
type BacktestServiceServer interface {
	RunBacktest(*BacktestConfig, grpc.ServerStreamingServer[BacktestProgress]) error
	GetBacktestResult(context.Context, *BacktestId) (*BacktestResult, error)
	ListBacktests(context.Context, *Empty) (*BacktestList, error)
	CompareStrategies(context.Context, *CompareRequest) (*CompareResult, error)
	mustEmbedUnimplementedBacktestServiceServer()
}

// UnimplementedBacktestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBacktestServiceServer struct{}

func (UnimplementedBacktestServiceServer) RunBacktest(*BacktestConfig, grpc.ServerStreamingServer[BacktestProgress]) error {
	return status.Error(codes.Unimplemented, "method RunBacktest not implemented")
}
func (UnimplementedBacktestServiceServer) GetBacktestResult(context.Context, *BacktestId) (*BacktestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBacktestResult not implemented")
}
func (UnimplementedBacktestServiceServer) ListBacktests(context.Context, *Empty) (*BacktestList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBacktests not implemented")
}
func (UnimplementedBacktestServiceServer) CompareStrategies(context.Context, *CompareRequest) (*CompareResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareStrategies not implemented")
}
func (UnimplementedBacktestServiceServer) mustEmbedUnimplementedBacktestServiceServer() {}
func (UnimplementedBacktestServiceServer) testEmbeddedByValue()                         {}

// UnsafeBacktestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BacktestServiceServer will
// result in compilation errors.
type UnsafeBacktestServiceServer interface {
	mustEmbedUnimplementedBacktestServiceServer()
}

func RegisterBacktestServiceServer(s grpc.ServiceRegistrar, srv BacktestServiceServer) {
	// If the following call panics, it indicates UnimplementedBacktestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BacktestService_ServiceDesc, srv)
}

func _BacktestService_RunBacktest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BacktestConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BacktestServiceServer).RunBacktest(m, &grpc.GenericServerStream[BacktestConfig, BacktestProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BacktestService_RunBacktestServer = grpc.ServerStreamingServer[BacktestProgress]

func _BacktestService_GetBacktestResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BacktestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServiceServer).GetBacktestResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BacktestService_GetBacktestResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServiceServer).GetBacktestResult(ctx, req.(*BacktestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _BacktestService_ListBacktests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServiceServer).ListBacktests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BacktestService_ListBacktests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServiceServer).ListBacktests(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BacktestService_CompareStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServiceServer).CompareStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BacktestService_CompareStrategies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServiceServer).CompareStrategies(ctx, req.(*CompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BacktestService_ServiceDesc is the grpc.ServiceDesc for BacktestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BacktestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradefox.nautilus.BacktestService",
	HandlerType: (*BacktestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBacktestResult",
			Handler:    _BacktestService_GetBacktestResult_Handler,
		},
		{
			MethodName: "ListBacktests",
			Handler:    _BacktestService_ListBacktests_Handler,
		},
		{
			MethodName: "CompareStrategies",
			Handler:    _BacktestService_CompareStrategies_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunBacktest",
			Handler:       _BacktestService_RunBacktest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nautilus/proto/nautilus.proto",
}

const (
	DataService_ListInstruments_FullMethodName = "/tradefox.nautilus.DataService/ListInstruments"
	DataService_ImportData_FullMethodName      = "/tradefox.nautilus.DataService/ImportData"
	DataService_GetDataRange_FullMethodName    = "/tradefox.nautilus.DataService/GetDataRange"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	ListInstruments(ctx context.Context, in *InstrumentFilter, opts ...grpc.CallOption) (*InstrumentList, error)
	ImportData(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImportProgress], error)
	GetDataRange(ctx context.Context, in *DataRangeRequest, opts ...grpc.CallOption) (*DataRange, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) ListInstruments(ctx context.Context, in *InstrumentFilter, opts ...grpc.CallOption) (*InstrumentList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstrumentList)
	err := c.cc.Invoke(ctx, DataService_ListInstruments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ImportData(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImportProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], DataService_ImportData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportRequest, ImportProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_ImportDataClient = grpc.ServerStreamingClient[ImportProgress]

func (c *dataServiceClient) GetDataRange(ctx context.Context, in *DataRangeRequest, opts ...grpc.CallOption) (*DataRange, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataRange)
	err := c.cc.Invoke(ctx, DataService_GetDataRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	ListInstruments(context.Context, *InstrumentFilter) (*InstrumentList, error)
	ImportData(*ImportRequest, grpc.ServerStreamingServer[ImportProgress]) error
	GetDataRange(context.Context, *DataRangeRequest) (*DataRange, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) ListInstruments(context.Context, *InstrumentFilter) (*InstrumentList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstruments not implemented")
}
func (UnimplementedDataServiceServer) ImportData(*ImportRequest, grpc.ServerStreamingServer[ImportProgress]) error {
	return status.Error(codes.Unimplemented, "method ImportData not implemented")
}
func (UnimplementedDataServiceServer) GetDataRange(context.Context, *DataRangeRequest) (*DataRange, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataRange not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_ListInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstrumentFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ListInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_ListInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ListInstruments(ctx, req.(*InstrumentFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ImportData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).ImportData(m, &grpc.GenericServerStream[ImportRequest, ImportProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_ImportDataServer = grpc.ServerStreamingServer[ImportProgress]

func _DataService_GetDataRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetDataRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetDataRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetDataRange(ctx, req.(*DataRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradefox.nautilus.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInstruments",
			Handler:    _DataService_ListInstruments_Handler,
		},
		{
			MethodName: "GetDataRange",
			Handler:    _DataService_GetDataRange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ImportData",
			Handler:       _DataService_ImportData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nautilus/proto/nautilus.proto",
}
